feat: database upload modal rather than multiple upload buttons
dhis2-sre/im-web-client pull request #164
Opened 2023-07-14 21:14 UTC by tonsV2

The goal of this PR is to implement a global upload database button at the top of the page rather than a button associated with each group. The reason for this is that it's more aligned with the original design for the application.

There are two unresolved issues that I'd appreciate some support on
* Loading indicator is displayed within form rather than on top of everything
* The selected file isn't shown
*

2023-07-18 09:21 UTC, HendrikThePendric requested changes
I don't really agree with these changes as they pollute the databases list component with code that does no have to do with listing. In my opinion we need one single component that:
1. Renders a button that can be clicked to show the modal
2. Contains the internal state for showing the modal
3. Conditionally renders the modal

In React each component needs a single root "element", but our modal and button are siblings. For these cases we can use the `React.Fragment` (<></>) as root element. So you'd get something like this:
```jsx
<>
    <Button />
    <Modal />    
</>
```

So the above is about architecture, but we also need to discuss naming. I understand your rename from `-button` to `-modal` given the current changes, but taking my suggestion into account this renaming no longer makes sense. And a good descriptive name is actually pretty difficult to come up with here. The component is a button that shows a modal, but it's not a `UploadModalButton` or a `UploadButtonModal`. 
1. I suppose `DatabaseUploadButtonWithProgressModal` would be accurate, but that's quite a long name...
2. Another approach to naming we could use to end up with a shorter name would be to not describe what the component _is_ but rather what the component _does_. This way we could opt for something like `DatabaseUploader`.

In general I prefer approach nr. 1 because it makes it easier to translate what you see in the code editor to what you see on your screen. I tend to only fallback to approach nr. 2 if the name would become ridiculously long, or if I simply can't come up with a good descriptive name at all.

2023-07-18 15:13 UTC, radnov reviewed
The changes are deployed to https://im.feat-consistent-uoload-da.test.c.dhis2.org


I noticed one issue so far - clicking "Upload" without selecting any local files will succeed and upload an empty file named `blob`:
![image](https://github.com/dhis2-sre/im-web-client/assets/8098421/dac8bf4f-f8b4-4dd7-b8e2-9c28c621c814)

2023-07-20 09:21 UTC, HendrikThePendric approved these changes

2023-07-20 10:14 UTC, radnov approved these changes

2023-07-20 13:51 UTC, merged