feat: update the status colors of instances
dhis2-sre/im-web-client pull request #481
Opened 2024-06-18 11:14 UTC by Chisomchima

implements [DEVOPS-304](https://dhis2.atlassian.net/browse/DEVOPS-304)
---

### Description
updated the already existing instance status color to suit spec.

2024-06-19 14:10 UTC, tonsV2 requested changes
Please run `yarn format` before you push :pray:

2024-06-19 14:10 UTC, tonsV2 commented on src/views/instances/details/status-label.tsx
> +    if (status.includes('Booting') || status === 'Pending') {
Why not use `startsWith`? It's more confined

2024-06-24 14:05 UTC, Mohammer5 requested changes
When I open the UI with one instance (`feat-public-deployments` as `ENVIRONMENT` in the `.env` file), the instance has two tags (`dhis2-db` and `dhis2-core`).

* Requested change: The url for both statuses is the same, so we could load the status once, per instance, instead of per tag
* Issue when reviewing: The actual request response with a 409 (twice, as there are two tags) with the following message: `multiple pods found using the selector: "im-default=true,im-id=2"`

Not sure why I'm getting an error? (cc @tonsV2)

2024-06-24 16:59 UTC, tonsV2 commented
> When I open the UI with one instance (`feat-public-deployments` as `ENVIRONMENT` in the `.env` file), the instance has two tags (`dhis2-db` and `dhis2-core`).
> 

There are two tags because there are two instances running within the cluster. Server side an instance is actually called a deployment and consist of multiple instances. Those instances could be dhis2-core as you're used to but also a Postgresql instance, a Redis instance or a MinIO (S3) instance.

> * Requested change: The url for both statuses is the same, so we could load the status once, per instance, instead of per tag

In this case they're the same and hopefully they usually both end up in the same state (running). However it's unlikely before they get there they go through multiple states and often not at the same time. We have talked about showing only an aggregated state one the list view but we haven't implemented it yet.

> * Issue when reviewing: The actual request response with a 409 (twice, as there are two tags) with the following message: `multiple pods found using the selector: "im-default=true,im-id=2"`
> 
> Not sure why I'm getting an error? (cc @tonsV2)

This can happen due to several things but it's most likely because an instance was evicted from one node only to be respawned on a different node.
We haven't updated the "get status" code to deal with this yet.

For the ensuring this is dealt with I've created this [Jira](https://dhis2.atlassian.net/browse/DEVOPS-414) task.

2024-06-24 18:46 UTC, Chisomchima commented
> * Requested change: The url for both statuses is the same, so we could load the status once, per instance, instead of per tag
> * Issue when reviewing: The actual request response with a 409 (twice, as there are two tags) with the following message: `multiple pods found using the selector: "im-default=true,im-id=2"`

Each instance contains different tags with different  tag Ids... hence the need to make seperate calls. also a tag represents an instance in a deployment.

2024-06-24 19:12 UTC, Chisomchima commented on src/views/instances/list/instances-list.tsx
> +import { Heading } from '../../../components'
Nice observation!

2024-06-25 13:18 UTC, Chisomchima commented on src/views/instances/list/instances-list.tsx
> -
done this

2024-06-25 13:22 UTC, Chisomchima commented
> Please run `yarn format` before you push 🙏

"After running 'yarn format' and 'yarn lint', I noticed significant changes to files I hadn't modified, suggesting that these commands hadn't been executed in previous commits and are now having a broader impact."

2024-06-25 13:39 UTC, tonsV2 approved these changes

2024-06-25 13:39 UTC, tonsV2 commented on src/utils/tag-utils.ts
How about just naming this file "tag.ts". The utils part is redundant :slightly_smiling_face:

2024-06-25 13:58 UTC, Chisomchima commented on src/utils/tag-utils.ts
done

2024-06-26 13:41 UTC, Mohammer5 approved these changes

2024-06-26 14:53 UTC, merged