feat: add confirm password input to pg admin
dhis2-sre/im-web-client pull request #507
Opened 2024-07-11 22:07 UTC by Chisomchima

Implements [DEVOPS-426](https://dhis2.atlassian.net/browse/DEVOPS-426)
---

### Description
confirm password input is added to the pgAdmin section when creating an instance with validation.

<img width="1136" alt="image" src="https://github.com/user-attachments/assets/6b8fc383-92f7-43fd-b353-5ceaf1d39ca0">

2024-07-15 10:13 UTC, tonsV2 approved these changes

2024-07-15 13:51 UTC, Mohammer5 requested changes

2024-07-15 13:51 UTC, Mohammer5 commented on src/hooks/use-dhis2-deployment.ts
> +                        pgadmin: valuesWithoutConfirmPassword,
```suggestion
                        [STACK_NAMES.PG_ADMIN]: valuesWithoutConfirmPassword,
```

2024-07-15 13:51 UTC, Mohammer5 commented on src/hooks/use-dhis2-deployment.ts
> +                        pgadmin: valuesWithoutConfirmPassword,
`STACK_NAMES` could go into its own file (`src/constants.ts`), then these values could be used everywhere. Right now we have the constants here, but everywhere else we're using the strings directly. I made a comment in the other PR about constants. If we have a constants file, we could put those constants into `src/constants.ts` as well

2024-07-16 08:11 UTC, Mohammer5 commented on src/hooks/use-dhis2-stack-parameters.ts
> +        if (stackName === 'pgadmin' && stack?.parameters) {
Could use the constant

2024-07-16 11:16 UTC, Mohammer5 approved these changes

2024-07-16 11:16 UTC, merged