feat: link to pgadmin in details page
dhis2-sre/im-web-client pull request #509
Opened 2024-07-12 07:18 UTC by Chisomchima

Implements [DEVOPS-427](https://dhis2.atlassian.net/browse/DEVOPS-427)
---

### Description
User should be able to view pgadmin instance directly from the instances details page.

https://github.com/user-attachments/assets/6c5c8cfd-6b20-45e8-8839-8729e770dc72

2024-07-15 13:34 UTC, Mohammer5 requested changes
I think this is generally good! Just have two minor comments

2024-07-15 13:34 UTC, Mohammer5 commented on src/views/instances/details/view-instance-menu-item.tsx
> +}
No need for a function (unless this causes performance issues, which it most likely never will).
Makes it easier to read:

```suggestion
export const ViewInstanceMenuItem: FC<ViewInstanceMenuItemProps> = ({
    groupName,
    name,
    stackName,
}) => {
    const host = `${groupName}.im.dhis2.org`
    const path = stackName ? `${name}-pgadmin` : name
    const url = `${host}/${path}`

    return (
        <MenuItem
            dense
            label="Open Instance"
            icon={<IconLaunch16 />}
            onClick={() => window.open(url, '_blank', 'noopener,noreferrer')}
        />
}
```

2024-07-15 13:34 UTC, Mohammer5 commented on src/views/instances/details/actions-dropdown-menu.tsx
> +                        {stackName !== 'dhis2-db' && <ViewInstanceMenuItem groupName={groupName} name={name} stackName={stackName} />}
It's clear how the condition evaluates, but the code doesn't provide any hint about **why** this happens.
In this case, I think it'd make sense to have a constant `VIEWABLE_INSTANCE_TYPES` (could be in `src/views/instances/details/constants.ts`)

Then we can change the condition from `stackName !== 'dhis2-db'` to `!VIEWABLE_INSTANCE_TYPES.includes(stackName)`, which makes this code expressive & declarative while keeping it explicit.

2024-07-15 13:38 UTC, Mohammer5 commented on src/views/instances/details/actions-dropdown-menu.tsx
> +                        {stackName !== 'dhis2-db' && <ViewInstanceMenuItem groupName={groupName} name={name} stackName={stackName} />}
Same applies to the condition in the other file

2024-07-16 08:12 UTC, Mohammer5 approved these changes

2024-07-16 09:27 UTC, tonsV2 approved these changes

2024-07-16 10:04 UTC, merged