refactor: upgrade from CRA to Vite
dhis2-sre/im-web-client pull request #512
Opened 2024-07-16 08:42 UTC by Mohammer5

2024-07-18 09:20 UTC, HendrikThePendric approved these changes
Left a few comments, but only minor points, so LGTM 🚀

2024-07-18 09:20 UTC, HendrikThePendric commented on .eslintrc.cjs
> +  env: { browser: true, es2020: true },
👍 we need this to be ES2020 to support optional chaining.

2024-07-18 09:20 UTC, HendrikThePendric commented on .eslintrc.cjs
> +    'plugin:react-hooks/recommended',
Perhaps this is the same as before.... I just wonder if we should not use the DHIS2 ESLint rules here?

2024-07-24 12:48 UTC, Chisomchima approved these changes
lgtm

2024-07-25 09:09 UTC, tonsV2 requested changes

2024-07-25 09:28 UTC, Mohammer5 commented on .prettierrc.cjs
> +// const { config } = require('@dhis2/cli-style')
Good catch!

2024-07-25 09:35 UTC, Mohammer5 commented on Dockerfile
> +FROM node:20 AS builder
Yes:

* Node 19 is not LTS. In the node-verse [only even version numbers will have LTS](https://nodejs.org/en/about/previous-releases)
* Many libraries support either node 18 or node 20. It's an issue I encountered after upgrading to vite.

2024-07-25 09:48 UTC, Mohammer5 commented on Makefile
> +	yarn install --frozen-lockfile && yarn test
Tests failed, I'm not sure exactly why.
But why do we need docker to run unit tests? Seems a little excessive

2024-07-25 09:48 UTC, Mohammer5 commented on src/views/databases/upload-database-modal.tsx
> +import {
prettier was set to 80 chars per line

2024-07-25 09:52 UTC, Mohammer5 commented on .prettierignore
I wouldn't, just what causes issues. I'd prefer if everything is aligned with our code-style

2024-07-25 09:54 UTC, tonsV2 commented on Dockerfile
> +FROM node:20 AS builder
But we can still use node:20-alpine, right?

2024-07-25 10:02 UTC, tonsV2 commented on Makefile
> +	yarn install --frozen-lockfile && yarn test
The philosophy is that you only have one dependency (which is Docker). You don't have to deal with versions etc.

2024-07-25 10:11 UTC, tonsV2 commented on src/views/databases/upload-database-modal.tsx
> +import {
But we change that back now so this shouldn't be changed, right?

2024-07-25 10:33 UTC, Mohammer5 commented on src/views/databases/upload-database-modal.tsx
> +import {
I'll address this once the general changes have been approved.
Then I'll run the linter as that will change much more.
I'll request another review from you at that point

2024-07-25 10:56 UTC, tonsV2 approved these changes

2024-07-25 11:56 UTC, tonsV2 approved these changes

2024-07-25 14:47 UTC, merged