fix: improve instance details styling
dhis2-sre/im-web-client pull request #514
Opened 2024-07-17 08:36 UTC by Chisomchima

Implements [DEVOPS-419](https://dhis2.atlassian.net/browse/DEVOPS-419)
---

### Description
This pull request enhances the instance details page styling.

---
<img width="1432" alt="image" src="https://github.com/user-attachments/assets/e09c6974-652c-497a-b373-f66b65841086">

2024-07-19 16:29 UTC, tonsV2 requested changes

2024-07-19 16:29 UTC, tonsV2 commented on src/views/instances/details/deployment-summary.tsx
> +                    <p>Created {deployment.createdAt ? <Moment date={deployment.createdAt} fromNow /> : ' - '}</p>
Most, if not all, of these properties such as createdAt, updatedAt etc. are always there so there shouldn't be a need to assert their presence

2024-07-22 07:17 UTC, Mohammer5 requested changes

2024-07-22 07:17 UTC, Mohammer5 commented on src/views/instances/details/deployment-summary.tsx
> +            <hr className={styles.hr} />
`hr`s should only be used when semantically correct (see [here](https://stackoverflow.com/a/9901454)).
In this case, it's there only for styling purposes, which can be done purely with CSS

2024-07-22 11:00 UTC, Mohammer5 approved these changes

2024-07-22 11:14 UTC, merged